// Code generated by mockery v2.50.4. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"

	mock "github.com/stretchr/testify/mock"
)

// AuthenticationHandler is an autogenerated mock type for the AuthenticationHandler type
type AuthenticationHandler struct {
	mock.Mock
}

// CmsSignInWithGoogle provides a mock function with given fields: c
func (_m *AuthenticationHandler) CmsSignInWithGoogle(c *gin.Context) {
	_m.Called(c)
}

// OrganizationSignInWithGoogle provides a mock function with given fields: c
func (_m *AuthenticationHandler) OrganizationSignInWithGoogle(c *gin.Context) {
	_m.Called(c)
}

// RefreshToken provides a mock function with given fields: c
func (_m *AuthenticationHandler) RefreshToken(c *gin.Context) {
	_m.Called(c)
}

// NewAuthenticationHandler creates a new instance of AuthenticationHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthenticationHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthenticationHandler {
	mock := &AuthenticationHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
