// Code generated by mockery v2.50.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// OrganizationCategoryUserHandler is an autogenerated mock type for the OrganizationCategoryUserHandler type
type OrganizationCategoryUserHandler struct {
	mock.Mock
}

// NewOrganizationCategoryUserHandler creates a new instance of OrganizationCategoryUserHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrganizationCategoryUserHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrganizationCategoryUserHandler {
	mock := &OrganizationCategoryUserHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
