// Code generated by mockery v2.50.4. DO NOT EDIT.

package mocks

import (
	models "server/internal/core/models"

	mock "github.com/stretchr/testify/mock"
)

// OrganizationUserUsecase is an autogenerated mock type for the OrganizationUserUsecase type
type OrganizationUserUsecase struct {
	mock.Mock
}

// CreateOrganizationUser provides a mock function with given fields: organizationUser
func (_m *OrganizationUserUsecase) CreateOrganizationUser(organizationUser *models.OrganizationUser) (*models.OrganizationUser, error) {
	ret := _m.Called(organizationUser)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrganizationUser")
	}

	var r0 *models.OrganizationUser
	var r1 error
	if rf, ok := ret.Get(0).(func(*models.OrganizationUser) (*models.OrganizationUser, error)); ok {
		return rf(organizationUser)
	}
	if rf, ok := ret.Get(0).(func(*models.OrganizationUser) *models.OrganizationUser); ok {
		r0 = rf(organizationUser)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.OrganizationUser)
		}
	}

	if rf, ok := ret.Get(1).(func(*models.OrganizationUser) error); ok {
		r1 = rf(organizationUser)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewOrganizationUserUsecase creates a new instance of OrganizationUserUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrganizationUserUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrganizationUserUsecase {
	mock := &OrganizationUserUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
