// Code generated by mockery v2.50.4. DO NOT EDIT.

package mocks

import (
	models "server/internal/core/models"

	mock "github.com/stretchr/testify/mock"
)

// OrganizationLogRepository is an autogenerated mock type for the OrganizationLogRepository type
type OrganizationLogRepository struct {
	mock.Mock
}

// CreateOrganizationLog provides a mock function with given fields: organizationLog
func (_m *OrganizationLogRepository) CreateOrganizationLog(organizationLog *models.OrganizationLog) (*models.OrganizationLog, error) {
	ret := _m.Called(organizationLog)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrganizationLog")
	}

	var r0 *models.OrganizationLog
	var r1 error
	if rf, ok := ret.Get(0).(func(*models.OrganizationLog) (*models.OrganizationLog, error)); ok {
		return rf(organizationLog)
	}
	if rf, ok := ret.Get(0).(func(*models.OrganizationLog) *models.OrganizationLog); ok {
		r0 = rf(organizationLog)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.OrganizationLog)
		}
	}

	if rf, ok := ret.Get(1).(func(*models.OrganizationLog) error); ok {
		r1 = rf(organizationLog)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewOrganizationLogRepository creates a new instance of OrganizationLogRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrganizationLogRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrganizationLogRepository {
	mock := &OrganizationLogRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
