// Code generated by mockery v2.50.4. DO NOT EDIT.

package mocks

import (
	models "server/internal/core/models"

	mock "github.com/stretchr/testify/mock"
)

// OrganizationCategoryServiceUsecase is an autogenerated mock type for the OrganizationCategoryServiceUsecase type
type OrganizationCategoryServiceUsecase struct {
	mock.Mock
}

// CreateOrganizationCategoryService provides a mock function with given fields: organizationCategoryService, requesterUserId
func (_m *OrganizationCategoryServiceUsecase) CreateOrganizationCategoryService(organizationCategoryService *models.OrganizationCategoryService, requesterUserId int) (*models.OrganizationCategoryService, error) {
	ret := _m.Called(organizationCategoryService, requesterUserId)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrganizationCategoryService")
	}

	var r0 *models.OrganizationCategoryService
	var r1 error
	if rf, ok := ret.Get(0).(func(*models.OrganizationCategoryService, int) (*models.OrganizationCategoryService, error)); ok {
		return rf(organizationCategoryService, requesterUserId)
	}
	if rf, ok := ret.Get(0).(func(*models.OrganizationCategoryService, int) *models.OrganizationCategoryService); ok {
		r0 = rf(organizationCategoryService, requesterUserId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.OrganizationCategoryService)
		}
	}

	if rf, ok := ret.Get(1).(func(*models.OrganizationCategoryService, int) error); ok {
		r1 = rf(organizationCategoryService, requesterUserId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteOrganizationCategoryService provides a mock function with given fields: organizationCategoryService, requesterUserId
func (_m *OrganizationCategoryServiceUsecase) DeleteOrganizationCategoryService(organizationCategoryService *models.OrganizationCategoryService, requesterUserId int) error {
	ret := _m.Called(organizationCategoryService, requesterUserId)

	if len(ret) == 0 {
		panic("no return value specified for DeleteOrganizationCategoryService")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.OrganizationCategoryService, int) error); ok {
		r0 = rf(organizationCategoryService, requesterUserId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewOrganizationCategoryServiceUsecase creates a new instance of OrganizationCategoryServiceUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrganizationCategoryServiceUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrganizationCategoryServiceUsecase {
	mock := &OrganizationCategoryServiceUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
